version: '3'

tasks:
  install-deps:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.3
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
      - go install github.com/envoyproxy/protoc-gen-validate@v1.2.1
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.26.0
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
      - go install github.com/pressly/goose/v3/cmd/goose@v3.24.1
      - go install github.com/rakyll/statik@v0.1.7

  get-deps:
    cmds:
      - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc

  local-migration-status:
    cmds:
      - goose -dir ${MIGRATION_DIR} postgres ${MIGRATION_DSN} status -v

  local-migration-up:
    cmds:
      - goose -dir ${MIGRATION_DIR} postgres ${MIGRATION_DSN} up -v

  local-migration-down:
    cmds:
      - goose -dir ${MIGRATION_DIR} postgres ${MIGRATION_DSN} down -v

  test:
    cmds:
      - go clean -testcache
      - go test ./... -v -coverpkg=github.com/astronely/financial-helper_microservices/noteService/internal/api/...,github.com/astronely/financial-helper_microservices/noteService/internal/service/...

  test-coverage:
    cmds:
      - go clean -testcache
      - go test ./... -coverprofile=coverage.tmp.out -covermode count -coverpkg=github.com/astronely/financial-helper_microservices/noteService/internal/api/...,github.com/astronely/financial-helper_microservices/noteService/internal/service/...
      - grep -v 'mocks\|config' coverage.tmp.out > coverage.out
      - rm coverage.tmp.out
      - go tool cover -html=coverage.out;
      - go tool cover -func=./coverage.out | grep "total";
      - grep -sqFx "/coverage.out" .gitignore || echo "/coverage.out" >> .gitignore

  generate:
    cmds:
      - task: generate-note-api

  generate-note-api:
    cmds:
      - if not exist pkg\note_v1 mkdir pkg\note_v1
      - protoc --proto_path api\note_v1 --proto_path vendor.protogen \
        --go_out=pkg\note_v1 --go_opt=paths=source_relative \
        --go-grpc_out=pkg\note_v1 --go-grpc_opt=paths=source_relative \
        --validate_out lang=go:pkg\note_v1 --validate_opt=paths=source_relative \
        --grpc-gateway_out=pkg\note_v1 --grpc-gateway_opt=paths=source_relative \
        api\note_v1\note.proto

  vendor-proto:
    cmds:
      - |
        if not exist vendor\protogen\validate (
          mkdir vendor\protogen\validate
          git clone https://github.com/envoyproxy/protoc-gen-validate vendor\protogen\protoc-gen-validate
          move vendor\protogen\protoc-gen-validate\validate\*.proto vendor\protogen\validate
          rmdir /s /q vendor\protogen\protoc-gen-validate
        )
      - |
        if not exist vendor\protogen\google (
          git clone https://github.com/googleapis/googleapis vendor\protogen\googleapis
          mkdir vendor\protogen\google
          move vendor\protogen\googleapis\google\api vendor\protogen\google
          rmdir /s /q vendor\protogen\googleapis
        )
      - |
        if not exist vendor\protogen\protoc-gen-openapiv2 (
          mkdir vendor\protogen\protoc-gen-openapiv2\options
          git clone https://github.com/grpc-ecosystem/grpc-gateway vendor\protogen\openapiv2
          move vendor\protogen\openapiv2\protoc-gen-openapiv2\options\*.proto vendor\protogen\protoc-gen-openapiv2\options
          rmdir /s /q vendor\protogen\openapiv2
        )
