version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:
  redis-data:

services:
  postgres-local:
    image: postgres:17.2-alpine3.21
    env_file:
      - "userService/local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine3.21
    env_file:
      - "userService/local.env"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
#  postgres-prod:
#    image: postgres:17.2-alpine3.21
#    env_file:
#      - "prod.env"
#    ports:
#      - "54322:5432"
#    volumes:
#      - postgres_volume_prod:/var/lib/postgresql/data
#
#  migrator-local:
#    build:
#      context: .
#      dockerfile: migration_local.Dockerfile
#    restart: on-failure
#    environment:
#      DB_HOST: postgres-local
#
#  migrator-prod:
#    build:
#      context: .
#      dockerfile: migration_prod.Dockerfile
#    restart: on-failure
#    environment:
#      DB_HOST: postgres-prod