version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:
  redis-data:

networks:
  backend:

services:
  postgres-local:
    image: postgres:17.2-alpine3.21
    env_file:
      - "userService/local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.4.2-alpine3.21
    env_file:
      - "userService/local.env"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  api-gateway:
    build:
      context: ./apiGateway
    image: astrow/api-gateway:latest
    env_file:
      - "./apiGateway/prod.env"
    depends_on:
      - user-service
      - auth-service
      - finance-service
      - note-service
      - board-service
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - backend

  user-service:
    build:
      context: ./userService
    image: astrow/user-service:latest
    env_file:
      - "./userService/prod.env"
    depends_on:
      - postgres-local
    ports:
      - "50051:50051"
    networks:
      - backend

  auth-service:
    build:
      context: ./authService
    image: astrow/auth-service:latest
    env_file:
      - "./authService/prod.env"
    depends_on:
      - postgres-local
    ports:
      - "50052:50052"
    networks:
      - backend

  finance-service:
    build:
      context: ./noteService
    image: astrow/finance-service:latest
    env_file:
      - "./financeService/prod.env"
    depends_on:
      - postgres-local
    ports:
      - "50053:50053"
    networks:
      - backend

  note-service:
    build:
      context: ./noteService
    image: astrow/note-service:latest
    env_file:
      - "./noteService/prod.env"
    depends_on:
      - postgres-local
    ports:
      - "50054:50054"
    networks:
      - backend

  board-service:
    build:
      context: ./boardService
    image: astrow/board-service:latest
    env_file:
      - "./boardService/prod.env"
    depends_on:
      - postgres-local
      - redis
    ports:
      - "50055:50055"
    networks:
      - backend