// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TokenConfig is an autogenerated mock type for the TokenConfig type
type TokenConfig struct {
	mock.Mock
}

// AccessTokenExpirationTime provides a mock function with no fields
func (_m *TokenConfig) AccessTokenExpirationTime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessTokenExpirationTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// AccessTokenKey provides a mock function with no fields
func (_m *TokenConfig) AccessTokenKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessTokenKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RefreshTokenExpirationTime provides a mock function with no fields
func (_m *TokenConfig) RefreshTokenExpirationTime() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenExpirationTime")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// RefreshTokenKey provides a mock function with no fields
func (_m *TokenConfig) RefreshTokenKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewTokenConfig creates a new instance of TokenConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenConfig {
	mock := &TokenConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
